export const categoriesList = [
    { name: 'Общие вопросы', icon: '/images/basic.svg' },
    { name: 'Бронирование', icon: '/images/booking.svg' },
    { name: 'Документы', icon: '/images/documents.svg' },
    { name: 'Гости', icon: '/images/guests.svg' },
    { name: 'Собственники', icon: '/images/owner.svg' },
    { name: 'Реклама', icon: '/images/ad.svg' },
    { name: 'Заселение/Выселение', icon: '/images/income.svg' },
    { name: 'Юридические вопросы', icon: '/images/uri.svg' },
    { name: 'Стоимость', icon: '/images/price.svg' },
    { name: 'Бухгалтерия', icon: '/images/buh.svg' },
    { name: 'Структура бизнеса', icon: '/images/structure.svg' },
    { name: 'IT', icon: '/images/it.svg' },
    { name: 'Расходники', icon: '/images/box.svg' },
    { name: 'Квартира', icon: '/images/home.svg' },
    { name: 'Ремонт', icon: '/images/repair.svg' },
    { name: 'Локации', icon: '/images/location.svg' },
    { name: 'Уборка', icon: '/images/cleaning.svg' },
];
